bungoCommerce/authent/urls.py
from django.urls import path
from . import views

app_name = "authent"
urlpatterns = [
    path("", views.index, name="index"),
    path("signin", views.signin, name="signin"),
    path("createuser", views.createuser, name="createuser"),
    path("loginuser", views.loginuser, name="loginuser"),
]

bungoCommerce/bungoCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('authent/', include("authent.urls")),
    path('commerce/', include("commerce.urls")),
    path('admin/', admin.site.urls),
]

# See, I had to do an exam while working on this, see the exam if you want:
# https://ikizkare.com/makale/turkce-7-sinif-deneme-20-soru-ve-cevaplari/1000
# 1: c, 2: a /, 3: d, 4: a, 5: a /, 6: c, 7: a, 8: d /, 9: d, 10: c, 11: c,
# 12: b, 13: a, 14: a, 15: d, 16: a, 17: c, 18: b, 19: d, 20: d

bungoCommerce/commerce/urls.py
from django.urls import path
from . import views

app_name = "commerce"
urlpatterns = [
    path("", views.index, name="index")
]

bungoCommerce/authent/models.py
from django.db import models

# Create your models here.

bungoCommerce/commerce/models.py
# pyright: reportGeneralTypeIssues=false

from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=250)
    price = models.FloatField(verbose_name="price", default=0.0)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return f"{self.name}: the price is {self.price}"

bungoCommerce/authent/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

# Create your views here.


def index(request):
    return render(request, "authent/index.html")


def User_unique(username):
    return not User.objects.filter(username=username).exists()


def Return_to_index_with_err(err, request):
    return render(request, "authent/index.html", {
        "err": err,
    })


def createuser(request):
    username = request.POST["username"]
    password = request.POST["password"]
    if len(username) <= 8 or len(password) <= 8:
        Return_to_index_with_err(
            "User name or password too short, please be sure they are longer than 8 characters", request)
    if User_unique(username):
        try:
            new_user = User.objects.create_user(
                username=username, password=password)
            new_user.save()

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
            else:
                Return_to_index_with_err(
                    "Could not authenticate user", request)

            print(request.POST)
            return HttpResponseRedirect(reverse("commerce:index"))
        except ValidationError as e:
            print(f"ValidationError: {e}")
            Return_to_index_with_err(
                "Could not validate user, please try again", request)
    else:
        Return_to_index_with_err("A user by that name already exists", request)


def signin(request):
    return render(request, "authent/login.html")


def loginuser(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("commerce:index"))
    else:
        return render(request, "authent/login.html", {
            "err": "Could not authenticate user"
        })

bungoCommerce/commerce/views.py
# pyright: reportGeneralTypeIssues=false

from django.shortcuts import render
from .models import Product

# Create your views here.


def index(request):
    return render(request, "commerce/index.html",
                  {"products": Product.objects.all()})

bungoCommerce/authent/templates/authent/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <form action="{% url 'authent:createuser' %}" method="post">
    {% csrf_token %}
    <fieldset>
      <legend>
        <h1>CREATE USER</h1>
      </legend>
      {% if err %}<h2>{{ err }}</h2>{% endif %}

      <input type="text" name="username" placeholder="User Name">
      <input type="password" name="password" placeholder="Password">
    </fieldset>
    <input type="submit" value="Sign Up">
  </form>
</body>

</html>

bungoCommerce/authent/templates/authent/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <form action="{% url 'authent:loginuser' %}" method="post">
    {% csrf_token %}
    <fieldset>
      <legend>
        <h1>LOG IN</h1>
      </legend>
      {% if err %}<h2>{{ err }}</h2>{% endif %}

      <input type="text" name="username" placeholder="User Name">
      <input type="password" name="password" placeholder="Password">
    </fieldset>
    <input type="submit" value="Log in">
  </form>
</body>

</html>

bungoCommerce/commerce/templates/commerce/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Bungo Commerce</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <header style="background-color: green; justify-content: center">
    <h1 class="display-4 text-center text-primary font-weight-bold">BUNGO COMMERCE</h1><br>
    <p>Bungo commerce is a commerce web application for you to see products and for me to learn django</p>
  </header>

  {% if user %}<h3>User: {{ user.username }}</h3>{% endif %}
  <a href="{% url 'authent:index' %}">Sign Up</a>
  <br>
  <a href="{% url 'authent:signin' %}">Log In</a>

  <ul>
    {% for p in products %}
    <div style="background-color: blue;">
      <h1>{{ p.name }}</h1>
      <h2>Price: {{ p.price }}$</h2>
      <img src="{% static p.image %}" style="margin: 10px;"></img>
    </div>
    {% endfor %}
  </ul>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>